In [55]:
import math as math

## 9. Los números telefónicos en la ciudad de Cuernavaca, Morelos, constan de siete dígitos.

<font size="4"> **a)** ¿Cuántas líneas telefónicas pueden crearse en esa ciudad? Recuerda que no pueden comenzar con cero.</font>


Para calcular el número posible de líneas telefónicas en Cuernavaca, Morelos necesitamos considerar lo siguiente:

- Cada número telefónico consta de siete dígitos.
- El primer dígito no puede ser cero.
- Los seis dígitos restantes pueden ser cualquier número del 0 al 9.

Asi que para poder determinar el número total de líneas telefónicas que podemos crear, debemos analizar las posibilidades para cada dígito:

- Primer dígito: Tenemos 9 opciones (del 1 al 9).

- Dígitos restantes: Para cada uno de los seis dígitos restantes, tenemos 10 opciones (del 0 al 9).

Por lo tanto el número total de líneas telefónicas se calcula multiplicando el número de posibilidades para cada dígito:

$$Número\ de\ líneas\ telefónicas = 9 \times 10^6$$

Siguiendo esta lógica, se pueden crear un total de **9,000,000** líneas telefónicas. Implementando la lógica en python se ve de esta manera: 

In [56]:
primer_digito = 9 # Primer digito (1 al 9)
digitos_restantes = 10 # Digitos restantes (0 al 9)

lineas_telefonicas = primer_digito * math.pow(digitos_restantes, 6)

print("El número total de líneas telefónicas posibles es:", lineas_telefonicas)


El número total de líneas telefónicas posibles es: 9000000.0


<font size="4"> **b)** Si los tres primeros dígitos representan una zona de Cuernavaca, ¿cuántas líneas telefónicas pertenecen a la zona 326? </font>

Para calcular el número de líneas telefónicas en la zona 326, necesitamos considerar lo siguiente:

- Hay dígitos fijos: Los números telefónicos de la zona 326 de Cuernavaca comienzan con los dígitos 3, 2 y 6. Estos tres primeros dígitos no pueden variar.
- Hay dígitos variables: Los últimos cuatro dígitos pueden ser cualquier número del 0 al 9, lo que nos da 10 opciones para cada uno de ellos.

Para determinar cuántas líneas telefónicas pertenecen a la zona 326, calculamos las combinaciones posibles de los últimos cuatro dígitos:

$$Número\ de\ líneas = 1 \times 10 \times 10 \times 10 \times 10 = 10^4$$

Al realizar este cálculo, obtenemos:

$$Número\ de\ líneas = 10,000$$

Asi que en la zona 326 de Cuernavaca, se pueden crear un total de **10,000** líneas telefónicas. Al igual, implementemos esa logica en python:

In [57]:
digitos_fijos = 1  # Los primeros tres dígitos están fijos, por lo que solo hay una opción
digitos_variables = 10  # Opciones para cada uno de los últimos cuatro dígitos (0-9)

lineas_zona_326 = digitos_fijos * math.pow(digitos_variables, 4)

print("b) El número de líneas telefónicas que se pueden crear en la zona 326 es:", lineas_zona_326)


b) El número de líneas telefónicas que se pueden crear en la zona 326 es: 10000.0


## 10. Se tiene la palabra MURCIÉLAGO. 
- ## Si no se permiten repeticiones al usar las letras que la forman, determina:


<font size="4"> **a)** El número de palabras que puedes crear.</font>

Imaginemos que tenemos 10 espacios en blanco para formar una palabra. 

En el primer espacio, podemos colocar cualquiera de las 10 letras disponibles. Para el segundo espacio, solo nos quedan 9 letras, ya que no puedes repetir la que ya usamos. En el tercer espacio, tendremos 8 opciones, y así sucesivamente.

Enotnces se puede decir que el número total de palabras posibles se obtiene multiplicando el número de opciones para cada espacio:

$$10\ opciones \times 9\ opciones \times 8\ opciones \times ... \times 2\ opciones \times 1\ opción$$

A esta operación matemática se le conoce como factorial y se denota con el símbolo "!". En este caso, sería $10!$ (factorial de 10).

Asi obtenemos que el factorial de 10 es:

$$10! = 3,628,800$$

Siguiendo la misma lógica en python podemos crear el siguiente codigo:

In [58]:
n_letras = 10  # Número de letras distintas
total_palabras = math.factorial(n_letras)

print("El número total de palabras posibles es:", total_palabras)


El número total de palabras posibles es: 3628800


<font size="4"> **b)** El número de palabras con cinco letras.</font>

Siguiendo la misma lógica que en el anterior, podemos visualizar 5 espacios en blanco para formar palabras de cinco letras. 

En el primer espacio, tenemos 10 opciones de letras. En el segundo, nos quedan 9 opciones, y así hasta el quinto espacio.

El número total de palabras de cinco letras se calcula multiplicando el número de opciones para cada espacio:

$$10\ opciones \times 9\ opciones \times 8\ opciones \times 7\ opciones \times 6\ opciones = 30,240$$

Por lo tanto, podemos formar un total de 30,240 palabras diferentes de cinco letras utilizando 10 letras distintas sin repetirlas.

Para mejorar la lógica del un código que escribiremos en python para resolver este inciso, podemos utilizar una fórmula matemática.

La fórmula para calcular las permutaciones es:

$$ P(n,k) = \dfrac{n!}{(n-k)!}$$

En donde:
- 𝑛 es el número total de letras disponibles (10 en este caso) 
- 𝑘 es el número de letras en cada palabra (5 en este caso). 

Reemplazando los valores en nuestra formula quedaria de la siguiente manera: 

$$ P(10,5) = \dfrac{10!}{(10-5)!}$$

Asi que esto se puede calcular de manera más eficiente usando la función math.perm en Python con el siguiente codigo:

In [59]:
n_letras = 10  # Número total de letras distintas
k_letras = 5   # Número de letras en cada palabra

# Calculamos el número de permutaciones de 10 letras tomando de 5 en 5
total_palabras = math.perm(n_letras, k_letras)

print("El número total de palabras de cinco letras es:", total_palabras)


El número total de palabras de cinco letras es: 30240


<font size="4"> **c)** La probabilidad de que una palabra de cinco letras termine en vocal.</font>

Para calcular la probabilidad de que una palabra de cinco letras termine en vocal tenemos que considerar que tenemos 5 vocales (A, E, I, O, U) en la palabra MURCIELAGO y tambien tenermos 5 consonantes en la palabra MURCIÉLAGO: M, R, C, L, G.

En el apartado anterior, calculamos que hay 30,240 palabras posibles de cinco letras con estas 10 letras distintas.

Para calcular la probabilidad tenemos que tener 2 cosas:

    1. Casos favorables
    2. Casos totales 

1. Los casos favorables:

- Para que una palabra termine en vocal, tenemos 5 opciones para la última letra.
- Las cuatro letras restantes se pueden elegir y ordenar de $P(9,4)$ maneras, que son las permutaciones de 9 elementos tomando de 4 en 4.

2. Casos totales:

- El número total de palabras de cinco letras es $P(10,5)$, que son las permutaciones de 10 elementos tomando de 5 en 5.


La probabilidad de que una palabra termine en vocal se calcula como:
$$Probabilidad = \frac{Casos\ favorables}{Casos\ totales}$$

Sustituyendo los valores en la formula quedaria de la siguiente forma:

$$Probabilidad = \frac{5 \times P(9,4)}{P(10,5)} = 0.5 = 50\%$$

Por lo tanto, la probabilidad de que una palabra de cinco letras termine en vocal es un 50%.

Ahora implementemos la logica en python, quedaria de la siguiente manera:

In [60]:
n_vocales = 5 # Número de vocales disponibles

total_letras = 10 # Número total de letras disponibles

letras_por_palabra = 5 # Número de letras en cada palabra

letras_restantes = total_letras - 1 # Número de letras restantes después de seleccionar una vocal para la última posición

# Permutaciones de 9 letras tomadas de 4 en 4 (para las 4 letras restantes después de elegir la vocal)
casos_favorables = n_vocales * math.perm(letras_restantes, letras_por_palabra - 1)

# Permutaciones de 10 letras tomadas de 5 en 5 (total de palabras de 5 letras)
casos_totales = math.perm(total_letras, letras_por_palabra)

# Cálculo de la probabilidad
probabilidad = casos_favorables / casos_totales

print("La probabilidad de que una palabra de cinco letras termine en vocal es:", probabilidad*100,"%") 


La probabilidad de que una palabra de cinco letras termine en vocal es: 50.0 %


## 16.  En un grupo de 25 alumnos hay 13 chicas y 12 chicos. Se desean formar equipos de trabajo para realizar una investigación:


<font size="4"> **a)** ¿Cuántos equipos de cinco personas pueden formarse?</font>

Para saber cuántos equipos de cinco personas pueden formarse a partir de un grupo de 25 alumnos, utilizaremos el concepto de combinaciones. 

Asi que para empezar en combinatoria, una combinación es una selección de elementos sin importar cual sea su orden.

La fórmula para calcular combinaciones es:

$$C(n,k) = \frac{n!}{k!(n-k)!}$$

donde:
- 𝑛 es el número total de elementos 
- 𝑘 es el número de elementos a seleccionar.

En este caso
- 𝑛=25 
- 𝑘=5

Si sustituimos estos valores en la fórmula, tenemos:

$$C(25,5) = \frac{25!}{5! (25-5)!} = \frac{25!}{5! \cdot 20!}$$

Podemos simplificar esto usando la propiedad de los factoriales:

$$C(25,5) = \frac{25 \times 24 \times 23 \times 22 \times 21}{5 \times 4 \times 3 \times 2 \times 1}$$

Calculamos el numerador y el denominador por separado:

$$25 \times 24 \times 23 \times 22 \times 21 = 6,\!375,\!600$$
$$5 \times 4 \times 3 \times 2 \times 1 = 120$$

Y al final, dividimos el numerador entre el denominador:

$$C(25,5) = \frac{6,\!375,\!600}{120} = 53,\!130$$

Por lo tanto, el número de equipos de cinco personas que pueden formarse es: $53130$
​





In [61]:
# Definimos los valores
n = 25
k = 5

# Calculamos las combinaciones usando la función comb de la biblioteca math
combinaciones = math.comb(n, k)

# Mostramos el resultado
print(f"El número de equipos de cinco personas que se pueden formar es: {combinaciones}")


El número de equipos de cinco personas que se pueden formar es: 53130


<font size="4"> **b)** ¿Cuántos equipos pueden formarse si debe haber una chica?</font>

Para calcular el número de equipos de cinco personas que deben incluir al menos una chica.

Primero, calculamos el número total de equipos posibles sin restricciones y luego restamos el número de equipos que no incluyen chicas.

1. Total de equipos posibles (sin restricciones):
    - Ya calculamos que hay $C(25,5)=53130$ equipos posibles.

2. Total de equipos sin chicas:
    - Hay 12 chicos. El número de equipos de cinco personas formados solo por chicos es $C(12,5)$.

Utilizamos la fórmula de combinaciones para calcular $C(12,5)$:

$$C(12,5) = \frac{12!}{5! (12-5)!} = \frac{12!}{5! \cdot 7!}$$

Simplificamos esto usando la propiedad de los factoriales:

$$C(12,5) = \frac{12 \times 11 \times 10 \times 9 \times 8}{5 \times 4 \times 3 \times 2 \times 1}$$

Calculamos el numerador y el denominador por separado:

$$12 \times 11 \times 10 \times 9 \times 8 = 95,040$$
$$5 \times 4 \times 3 \times 2 \times 1 = 120$$

Dividimos el numerador entre el denominador:

$$C(12,5) = \frac{95,040}{120} = 792$$

Entonces, hay 792 equipos de cinco personas formados solo por chicos.

Ahora calculemos los equipos con al menos una chica:

Solo hay que restar el número de equipos sin chicas del total de equipos posibles:

$$53130−792=52338$$

Por lo tanto, el número de equipos de cinco personas que incluyen al menos una chica es: $52338$
​


In [62]:
# Definimos los valores
total_alumnos = 25
total_chicos = 12
tamaño_equipo = 5

# Calculamos el número total de combinaciones posibles
total_combinaciones = math.comb(total_alumnos, tamaño_equipo)

# Calculamos el número de combinaciones solo con chicos
combinaciones_sin_chicas = math.comb(total_chicos, tamaño_equipo)

# Calculamos el número de combinaciones con al menos una chica
combinaciones_con_chicas = total_combinaciones - combinaciones_sin_chicas

# Mostramos el resultado
print(f"El número de equipos de cinco personas que se pueden formar con al menos una chica es: {combinaciones_con_chicas}")


El número de equipos de cinco personas que se pueden formar con al menos una chica es: 52338


<font size="4"> **c)** ¿Cuántos equipos pueden formarse si debe haber dos chicas?</font>

Para calcular el número de equipos de cinco personas que deben incluir exactamente dos chicas, podemos dividir el problema en dos partes:

- Seleccionamos 2 chicas de las 13 disponibles.
- Seleccionamos 3 chicos de los 12 restantes.

Utilizamos la fórmula de combinaciones para cada parte y luego multiplicamos los resultados:

$$C(13,2) \times C(12,3)$$

Vamos a calcular cada parte por separado:

1. Seleccionar 2 chicas de 13:

$$C(13,2) = \frac{13!}{2! (13-2)!} = \frac{13!}{2! \cdot 11!}$$

- Simplificamos usando la propiedad de los factoriales:

$$C(13,2) = \frac{13 \times 12}{2 \times 1} = 78$$

2. Seleccionar 3 chicos de 12:

$$C(12,3) = \frac{12!}{3! (12-3)!} = \frac{12!}{3! \cdot 9!}$$

- Simplificamos usando la propiedad de los factoriales:

$$C(12,3) = \frac{12 \times 11 \times 10}{3 \times 2 \times 1} = 220$$

Finalmente para terminar, multiplicamos los resultados para obtener el número total de equipos con exactamente dos chicas:

$$78×220=17160$$

Por lo tanto, el número de equipos de cinco personas que se pueden formar con exactamente dos chicas es: $17,160$

El codigo en python que resuelve este problema es el siguiente:

In [63]:
# Definimos los valores
total_chicas = 13
total_chicos = 12
chicas_a_seleccionar = 2
chicos_a_seleccionar = 3

# Calculamos el número de maneras de seleccionar dos chicas de 13
combinaciones_dos_chicas = math.comb(total_chicas, chicas_a_seleccionar)

# Calculamos el número de maneras de seleccionar tres chicos de 12
combinaciones_tres_chicos = math.comb(total_chicos, chicos_a_seleccionar)

# Calculamos el número total de combinaciones con exactamente dos chicas
combinaciones_dos_chicas_exactamente = combinaciones_dos_chicas * combinaciones_tres_chicos

# Mostramos el resultado
print(f"El número de equipos de cinco personas que se pueden formar con exactamente dos chicas es: {combinaciones_dos_chicas_exactamente}")


El número de equipos de cinco personas que se pueden formar con exactamente dos chicas es: 17160


<font size="4"> **d)** Determina las probabilidades correspondientes a los incisos anteriores.</font>

Para determinar las probabilidades, primero necesitamos conocer el número total de equipos posibles y luego usarlo para calcular las probabilidades para cada caso.

Como ya sabemos que el número total de equipos de cinco personas que se pueden formar es 53,130. 

Utilizaremos este número para calcular las probabilidades.

**Inciso (a)**

Probabilidad de formar un equipo de cinco personas (sin restricciones):

Este es el caso más simple, ya que estamos considerando todos los equipos posibles.

$$P(equipo sin restricciones)=1$$

La probabilidade de formar un equipo de cinco personas es del $100\%$

**Inciso (b)**

Probabilidad de formar un equipo de cinco personas con al menos una chica:

Sabemos que hay 52,338 equipos posibles que incluyen al menos una chica.

La probabilidad es:

$$P(\text{al menos una chica}) = \frac{53,\!130 - 792}{53,\!130} = \frac{52,\!338}{53,\!130}$$

La probabilidad de formar un equipo de cinco personas con al menos una chica es de:  $98.5\%$

**Inciso (c)**

Probabilidad de formar un equipo de cinco personas con exactamente dos chicas:

Sabemos que hay 17,160 equipos posibles con exactamente dos chicas.

La probabilidad es:

$$P(\text{exactamente dos chicas}) = \frac{17,\!160}{53,\!130} = \frac{17,\!160}{53,\!130}$$

La probabilidad de formar un equipo de cinco personas con exactamente dos chicas es de: $32.2\%$

Solo queda mostrar como calcular estas probabilidades con una mejor precisión utilizando python:

In [64]:
# Calculamos el número total de combinaciones posibles
total_combinaciones = math.comb(total_alumnos, tamaño_equipo)

# Calculamos el número de combinaciones con al menos una chica
# Primero calculamos el número de combinaciones sin chicas
combinaciones_sin_chicas = math.comb(total_chicos, tamaño_equipo)
# Luego restamos estas combinaciones del total
combinaciones_con_al_menos_una_chica = total_combinaciones - combinaciones_sin_chicas

# Calculamos el número de combinaciones con exactamente dos chicas
combinaciones_dos_chicas = math.comb(total_chicas, 2) * math.comb(total_chicos, 3)

# Cálculo de probabilidades
probabilidad_total = total_combinaciones / total_combinaciones
probabilidad_al_menos_una_chica = combinaciones_con_al_menos_una_chica / total_combinaciones
probabilidad_dos_chicas_exactamente = combinaciones_dos_chicas / total_combinaciones

# Mostrar resultados
print(f"Probabilidad de formar un equipo de cinco personas (sin restricciones): {probabilidad_total:.4f} ({probabilidad_total*100}%)")
print(f"Probabilidad de formar un equipo de cinco personas con al menos una chica: {probabilidad_al_menos_una_chica:.4f} ({probabilidad_al_menos_una_chica*100:.4f}%)")
print(f"Probabilidad de formar un equipo de cinco personas con exactamente dos chicas: {probabilidad_dos_chicas_exactamente:.4f} ({probabilidad_dos_chicas_exactamente*100:.4f}%)")


Probabilidad de formar un equipo de cinco personas (sin restricciones): 1.0000 (100.0%)
Probabilidad de formar un equipo de cinco personas con al menos una chica: 0.9851 (98.5093%)
Probabilidad de formar un equipo de cinco personas con exactamente dos chicas: 0.3230 (32.2981%)


## 17.  Se tiene una caja con 24 latas y se sabe que dos están contaminadas. Se van a seleccionar tres latas al azar para someterlas a una prueba de control de calidad, es decir, para medir los estándares de calidad de la empresa

<font size="4"> **a)** ¿Cuántas combinaciones de tres latas pueden hacerse?</font>

Para calcular cuántas combinaciones de tres latas pueden hacerse a partir de una caja con 24 latas, utilizaremos la fórmula de combinaciones. 

La fórmula para calcular combinaciones es:

$$C(n,k) = \frac{n!}{k!(n-k)!}$$

donde:
- 𝑛 es el número total de elementos 
- 𝑘 es el número de elementos a seleccionar.

En este caso
- 𝑛=24
- 𝑘=3

Sustituyendo estos valores en la fórmula, tenemos:
​
$$C(24,3) = \frac{24!}{3! (24-3)!} = \frac{24!}{3! \cdot 21!}$$

Podemos simplificar esto usando la propiedad de los factoriales:

$$C(24,3) = \frac{24 \times 23 \times 22}{3 \times 2 \times 1}$$ 

Calculamos el numerador y el denominador por separado:

$$24 \times 23 \times 22 = 12,\!144$$ 
$$3 \times 2 \times 1 = 6$$

Finalmente, dividimos el numerador entre el denominador:

$$C(24,3) = \frac{12,\!144}{6} = 2,\!024$$

Por lo tanto, el número de combinaciones de tres latas que pueden hacerse es: $2024$

El codigo en pyhton es el siguiente:



In [65]:
# Definimos los valores
n = 24
k = 3

# Calculamos las combinaciones usando la función comb de la biblioteca math
combinaciones = math.comb(n, k)

# Mostramos el resultado
print(f"El número de combinaciones de tres latas que se pueden formar es: {combinaciones}")


El número de combinaciones de tres latas que se pueden formar es: 2024


<font size="4"> **b)** ¿Cuál es la probabilidad de que se seleccione una lata contaminada para la prueba?</font>

Para calcular la probabilidad vamos a hacerlo por pasos, primero buscaremos un numero de formas para seleccionar una lata, usaremos el calculo del inciso 1 y despues la probabilidad de seleccionar exactamente una lata contaminada

1. Número de formas de seleccionar exactamente una lata contaminada:

   - Hay 2 latas contaminadas y 22 latas no contaminadas.
   - Necesitamos elegir 1 lata contaminada de las 2 disponibles y 2 latas no contaminadas de las 22 disponibles.


   La cantidad de formas de hacer esto es el resultado de la multiplicacion de las combinaciones correspondientes:

   
   $$C(2,1) \times C(22, 2)$$
   

   Calculando cada combinación:

   
   $$C(2,1) = \frac{2!}{1!(2-1)!} = 2$$
   

   
   $$C(22,2) = \frac{22!}{2!(22-2)!} = \frac{22 \times 21}{2} = 231$$
   

   Entonces, el número total de formas de seleccionar exactamente una lata contaminada es:

   
   $$C(2,1) \times C(22,2) = 2 \times 231 = 462$$

2. Número total de formas de seleccionar 3 latas de las 24 disponibles:

   
   $$C(24,3) = \frac{24!}{3!(24-3)!} = \frac{24 \times 23 \times 22}{3 \times 2 \times 1} = 2024$$
   

3. Probabilidad de seleccionar exactamente una lata contaminada:

   La probabilidad se calcula dividiendo el número de formas favorables entre el número total de formas posibles:

   
   $$P(\text{exactamente una lata contaminada}) = \frac{C(2,1) \times C(22,2)}{C(23,4)} = \frac{462}{2024} \approx 0.2282$$

Entonces la probabilidad de que exactamente una lata contaminada sea seleccionada en las tres latas elegidas al azar es aproximadamente $0.2282\ (22.8\%)$


In [66]:
# Número total de latas y número de latas contaminadas
total_latas = 24
contaminadas = 2

# Número de latas no contaminadas
no_contaminadas = total_latas - contaminadas

# Número de formas de seleccionar exactamente una lata contaminada y dos no contaminadas
num_combinaciones_contaminada = math.comb(contaminadas, 1)  # Seleccionar 1 lata contaminada de 2
num_combinaciones_no_contaminadas = math.comb(no_contaminadas, 2)  # Seleccionar 2 latas no contaminadas de 22

# Número total de formas de seleccionar 3 latas de 24
num_total_combinaciones = math.comb(total_latas, 3)

# Probabilidad de seleccionar exactamente una lata contaminada
probabilidad = (num_combinaciones_contaminada * num_combinaciones_no_contaminadas) / num_total_combinaciones

print(f"Probabilidad de seleccionar exactamente una lata contaminada: {probabilidad*100:.4f}%")


Probabilidad de seleccionar exactamente una lata contaminada: 22.8261%



<font size="4"> **c)** ¿Cuál es la probabilidad de que se seleccione al menos una lata contaminada para la prueba?</font>

Para calcular la probabilidad de que al menos una de las tres latas seleccionadas esté contaminada, primero debemos calcular la probabilidad de que ninguna de las tres latas seleccionadas esté contaminada. 

Despues, restamos esta probabilidad de 1.

Dado que hay 2 latas contaminadas en un total de 24, hay 22 latas no contaminadas.

1. Número de maneras de seleccionar 3 latas de las 22 no contaminadas:

$$C(22,3) = \frac{22!}{3! (22-3)!} = \frac{22!}{3! \cdot 19!} = \frac{22 \times 21 \times 20}{3 \times 2 \times 1} = 1540$$

2. Número total de maneras de seleccionar 3 latas de las 24:

$$C(24,3) = 2024$$

3. Probabilidad de seleccionar solo latas no contaminadas:

$$P(\text{ninguna contaminada}) = \frac{C(24,3)}{C(22,3)} = \frac{2024}{1540}$$

4. Probabilidad de seleccionar al menos una lata contaminada:

$$P(al menos una contaminada)=1−P(ninguna contaminada)=1− \frac{2024}{1540}$$

Calculamos la fracción:


$$P(ninguna contaminada)= \frac{2024}{1540}≈0.7603$$

$$P(al menos una contaminada)=1−0.7603=0.2391$$

Y asi podemos decir que la probabilidad de que se seleccione al menos una lata contaminada es de: $23.91\%$​

In [67]:
# Número total de latas y número de latas contaminadas
total_latas = 24
latas_contaminadas = 2
latas_no_contaminadas = total_latas - latas_contaminadas

# Calcular combinaciones totales de seleccionar 3 latas de 24
combinaciones_totales = math.comb(total_latas, 3)

# Calcular combinaciones de seleccionar 3 latas de las 22 no contaminadas
combinaciones_no_contaminadas = math.comb(latas_no_contaminadas, 3)

# Probabilidad de seleccionar al menos una lata contaminada
probabilidad_al_menos_una_contaminada = 1 - (combinaciones_no_contaminadas / combinaciones_totales)

print(f"La probabilidad de que al menos una lata contaminada sea seleccionada {probabilidad_al_menos_una_contaminada*100:.2f}%")


La probabilidad de que al menos una lata contaminada sea seleccionada 23.91%


<font size="4"> **d)** ¿Y la probabilidad de que no se elijan latas contaminadas para la prueba?</font>

Para calcular la probabilidad de que no se elijan latas contaminadas en las tres latas seleccionadas al azar, podemos seguir estos pasos:

1. Número de formas de seleccionar tres latas no contaminadas:

   - Hay 22 latas no contaminadas y 2 latas contaminadas.
   - Necesitamos elegir las 3 latas no contaminadas de las 22 disponibles.

   Utilizamos la fórmula de combinaciones para calcular esto:

   
   $$C(22, 3) = \frac{22 \times 21 \times 20}{3 \times 2 \times 1} = 1540$$
   

2. Número total de formas de seleccionar 3 latas de las 24 disponibles:

   
   $$C(24, 3) = \frac{24 \times 23 \times 22}{3 \times 2 \times 1} = 2024$$
   

3. Probabilidad de no seleccionar latas contaminadas:

   La probabilidad de que las 3 latas seleccionadas al azar no sean contaminadas se calcula dividiendo el número de formas favorables (seleccionar 3 latas no contaminadas) entre el número total de formas posibles (seleccionar cualquier combinación de 3 latas):

   
   $$P(\text{ninguna lata contaminada}) = \frac{C(22, 3)}{C(24, 3)} = \frac{1540}{2024} \approx 0.7603$$
   

La probabilidad de que no se elijan latas contaminadas en las tres latas seleccionadas al azar es aproximadamente $ 76.03\% $.

In [68]:

# Número total de latas y número de latas contaminadas
total_latas = 24

# Número de latas no contaminadas
no_contaminadas = total_latas - latas_contaminadas

# Número de formas de seleccionar ninguna lata contaminada
num_combinaciones_no_contaminadas = math.comb(no_contaminadas, 3)  # Seleccionar 3 latas no contaminadas de 22

# Número total de formas de seleccionar 3 latas de 24
num_total_combinaciones = math.comb(total_latas, 3)

# Probabilidad de no seleccionar latas contaminadas
probabilidad = num_combinaciones_no_contaminadas / num_total_combinaciones

print(f"Probabilidad de no seleccionar latas contaminadas es de: {probabilidad*100:.2f}%")

Probabilidad de no seleccionar latas contaminadas es de: 76.09%
